export enum EMuscleGroup {
  PECTORAL = 'PECTORAL',
  BACK = 'BACK',
  SHOULDERS = 'SHOULDERS',
  BICEPS = 'BICEPS',
  TRICEPS = 'TRICEPS',
  ABDOMEN = 'ABDOMEN',
  LEGS = 'LEGS',
  FOREARMS = 'FOREARMS',
}
